### PR TITLE
Prevent Double Navigation

### PR DESCRIPTION
**Pull request by ulfgebhardt**
**Issue:** #183

**Description:**

Prevent Double Navigation

**How to test:**

Not working yet, just the Stuff from the Internet

https://github.com/wix/react-native-navigation/issues/271

ALternative: https://github.com/wix/react-native-navigation/issues/2655

**Checklist:**
- [ ] Version
- [x] Changelog
- ~~[ ] BuildEnv Variables~~

### CODE REVIEW

**Comment by ReggaePanda** [comment]
bildschirmfoto 2018-04-11 um 16 10 49

**Comment by ReggaePanda** [comment]
double-open

**Comment by ReggaePanda** [comment]
alternativ könnten wir auch über apollo-link-state registrieren, was der user macht und das dadurch auch für iOS ermöglichen

**Comment by ulfgebhardt** [comment]
@ReggaePanda Please check on iOS if this works now

- Don't forget ```yarn``` to update react-native-navigation
- Don't merge this commit yet

**Pull request merged**
